version: '3.9'

services:
  database:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  tomcat:
    build: .
    container_name: tomcat_server
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  db_data: