version: '3.8'

services:
  tomcat:
    image: tomcat:11.0.2
    container_name: tomcat
    ports:
      - "8080:8080"  # Пробрасываем порт 8080 из контейнера на 8080 на хосте
    networks:
      - mynetwork
    volumes:
      - ./target/learning-session.war:/usr/local/tomcat/webapps/learning-session.war  # Монтируем .war файл
    depends_on:
      - postgres
    # Здесь можно добавить скрипт ожидания готовности базы данных, если требуется

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: learning-session  # Имя базы данных
      POSTGRES_USER: postgres  # Имя пользователя
      POSTGRES_PASSWORD: postgres  # Пароль пользователя
    ports:
      - "5432:5432"  # Пробрасываем порт PostgreSQL на хост
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Персистентное хранение данных PostgreSQL

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local
