CREATE DATABASE webapp;
CREATE TABLE users (
                       user_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       user_name VARCHAR(50) NOT NULL UNIQUE,
                       user_password VARCHAR(50) NOT NULL
);
INSERT INTO users (user_name, user_password) VALUES ('admin', 'admin');
